### ISSUE TITLE
Parser for log & exp & trig equations

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#218]
So... there should be a smart parser for exponential, logarithmic, and trigonometric expressions, so that we could easily extract 
polynomials from those functions

Some ideas: https://github.com/asc-community/AngouriMath/issues/188#issuecomment-672963297

**Comment by MomoDeve** [comment]
Since we already have linear polynome parser in integration branch, we only thing is missing now is the ability to represent expression as `a1 * f1(g1(x)) + a2 * f2(g2(x)) + ... + c = 0` where `g(x)` are linear functions (`ax+b`)

- for trigonometric equations `f(x)` are any of `[sin(x), cos(x), tan(x), cot(x)]`
- for exponential equations `f(x)` are `a^x`
- for logarithmic equations `f(x)` are `log(a, x)`

So here the main problem is to find a group of functions, for example: `a*2^x + b*4^x + c*8^x` should be matched by exponential parser so `[2, 4, 8]` can be easily retrived

**Comment by MomoDeve** [comment]
As exponential solver is done, the only one left is logarihtmic solver. [#246](https://github.com/asc-community/AngouriMath/issues/246) covers it, so this issue is redundant
