### ISSUE TITLE
Parse Entity from LaTeX

### ISSUE THREAD

**Issue by yoshiask** [asc-community/AngouriMath#292]
It feels weird that this library can generate LaTeX from an Entity, but not generate an Entity from LaTeX. I understand that it's much more difficult to do the reverse, but I think it's better to have a parser that works most of the time than not have that capability at all.

I'm already working on something like this, specifically for parsing functions, that utilizes `LaTeXParser.MathListFromLaTeX(string)` from CSharpMath to parse the LaTeX and then transform it into a string that AngouriMath should recognize.

**Comment by WhiteBlackGoose** [comment]
The problem with parsing LaTeX is that we either need to have a reinvented wheel for a naive LaTeX parser, or have a dependency on the LaTeX compiler (or whatever there is). To be honest, I don't know if it's really *that* needed: latex is more of output format, not sure where we can need to reverse it.

Do you know some usecases for it?

And since you mentioned that you're working on it already, are you planning to create a separate project which parses LaTeX to Entity?

**Comment by yoshiask** [comment]
You're right that LaTeX is usually an output format, but there are some cases where it's not. For example, Desmos uses LaTeX (via [MathQuill](http://mathquill.com/)) as an input. If you paste some LaTeX into a cell in Desmos, such as `f(x)=10\sin\left(\frac{x}{10}\right)`, it will evaluate it.

I can pretty easily move it into it's own project (and I probably should anyway). Right now the entire logic is in a single recursive function, so it can reasonably be a single class.

**Comment by WhiteBlackGoose** [comment]
@yoshiask just to warn you. I hope you are either using repo's master or a 1.2 preview version. Because if you are on 1.1, it is quite outdated, and you will have to rewrite quite a lot once 1.2 is released

**Comment by Happypig375** [comment]
@yoshiask CSharpMath does have a method to create an AngouriMath Entity from LaTeX. https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath.Evaluation/Evaluation.cs

It's not updated to AngouriMath 1.2 though.

**Comment by WhiteBlackGoose** [comment]
So I guess you will be able to enjoy parsing from LaTeX once CSharpMath is upgraded to AngouriMath 1.2.
