### ISSUE TITLE
Numerical matrix comparison with a specified precision gives the wrong result

### ISSUE THREAD

**Issue by lambrtz** [asc-community/AngouriMath#502]
The code below checks if the matrices `matrix` and `identity` are equal within a specified tolerance. They are supposed to be equal, but the comparison returns `false`.

Here is an MWE:

```
using AngouriMath; using AngouriMath.Extensions; using static AngouriMath.MathS; using static AngouriMath.Entity; using System; using static System.Console;
using PeterO.Numbers;

Entity.Matrix matrix = "[[1.000000000000000547458310833800074927650525249394612805610000, 0, 0, -9.55753574799863785565952768061466479249665075036612773690000E-15], [0, 1.000000000000000547458310833800074927650525249394612805610000, 0, 2.24075209004037969624007863746621061783995000E-15], [0, 0, 1, 0], [0, 0, 0, 1]]";
var identity = MathS.IdentityMatrix(4);
using var _ = MathS.Settings.PrecisionErrorCommon.Set(0.1m);
WriteLine(matrix == identity);
```

Output:
```
False
```

**Comment by WhiteBlackGoose** [comment]
@lambrtz Thanks for reporting! The issue has been fixed. Use `.EqualsImprecisely` now to compare entities, and let me know if you run into issues.

The fix will be available since the next release. If you want it ASAP, you can get the current master build as described [here](https://am.angouri.org/quickstart/#dotnet)

**Comment by WhiteBlackGoose** [comment]
Wait. I made a mistake. The issue is more complicated, actually
