### ISSUE TITLE
Logical calculation 

### ISSUE THREAD

**Issue by chrismx000** [asc-community/AngouriMath#604]
hi.In my project how many parameters are deciding by user And it will use Logical calculation
 just like "a+b>0 and c<0 or d>5 and not e".
In example i found that 
Entity expr = "a and x > 3";
var func = expr.Compile<bool, double, bool>("a", "x");
WriteLine(func(true, 6));
but  if i have  more than 8 parameters ，what should I do？

**Comment by chrismx000** [comment]
But the number of parameters are design by users.So the method of  expr.Compile<Func<TDeleage>>(.....)   is hard to use in my case.....is any other way else?

**Comment by WhiteBlackGoose** [comment]
I see.

## 1. Reflectoin (easy way)

You (theoreticall) can construct type `Func` on the fly, using `typeof(Func<>)` and method `MakeGeneric`, and then invoking method Compile using reflection too

## 2. Rewriting the compiler (hard way)

There's also old compiler, which is as simple as
```cs
myExpr.Compile("a", "b", "c")
```
It returns `FastExpression` type instead of a delegate. It isn't as fast as delegate, but its main problem is that it's far less feature-rich ([here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoFE/FastExpression.cs) is the interpreter, [here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoFE/Compiler.cs) is the compiler).

And becuse it's not as feature rich, to make it work you will have to fork AngouriMath and
1. Add bool operators to the compiler and interpreter (it's not too hard, changes are expected [here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoFE/FastExpression.cs#L16), [here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoFE/FastExpression.cs#L91), and [here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoFE/Compiler.cs#L81))
2. Make `FastExpression.Substitute` return a bool (or make `SubstituteBool` or something)

**Comment by chrismx000** [comment]
thanks a lot. I will try it later。
