### ISSUE TITLE
Simplification given a variable is in a set

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#75]
e.g. Given x >= 0, we can simplify sqrt(x^2) to x, and -x given x < 0.

**Comment by WhiteBlackGoose** [comment]
Not now

**Comment by Happypig375** [comment]
Why not leave this open for the future?

**Comment by Happypig375** [comment]
Why not leave this open for the future?

**Comment by Happypig375** [comment]
𝖶𝗁𝗒 𝗇𝗈𝗍 𝗅𝖾𝖺𝗏𝖾 𝗍𝗁𝗂𝗌 𝗈𝗉𝖾𝗇 𝖿𝗈𝗋 𝗍𝗁𝖾 𝖿𝗎𝗍𝗎𝗋𝖾?

**Comment by WhiteBlackGoose** [comment]
Because it is not an issue, it's more like proposal "build a spaceship to the moon" while we just discovered how to construct a hammer of sticks and stones.

What you are talking about is probably Piecewise and it is just another far feature that we keep in mind because our "competitors", to be precise, SymPy, have it.

**Comment by WhiteBlackGoose** [comment]
Sorry I sometimes miss messages
